### ISSUE TITLE
NPE reported after installation of plugin

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-resources-convertor#18]
[ AWT-EventQueue-0 ]  -  java.lang.NullPointerException
                java.lang.NullPointerException
                    at com.oxygenxml.resources.batch.converter.plugin.CustomWorkspaceAccessPluginExtension.addActionsInMenuBar(CustomWorkspaceAccessPluginExtension.java:122)
                    at com.oxygenxml.resources.batch.converter.plugin.CustomWorkspaceAccessPluginExtension.access$000(CustomWorkspaceAccessPluginExtension.java:29)
                    at com.oxygenxml.resources.batch.converter.plugin.CustomWorkspaceAccessPluginExtension$1.customizeMainMenu(CustomWorkspaceAccessPluginExtension.java:60)

**Comment by DunaMariusCosmin** [comment]
Fixed in: d9792b9431da1cbf5eddafd3b6e1755e56237c7d
